Resources:

  MyBucket:
    Type: AWS::S3::Bucket

  MyDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt MyBucket.RegionalDomainName
            S3OriginConfig: {}

        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: allow-all
          ForwardedValues:
            QueryString: false

Outputs:

  BucketName:
    Value: !Ref MyBucket

  CloudFrontURL:
    Value: !GetAtt MyDistribution.DomainName
